Adding an example to readme file
tylerlaceby/multipart pull request #1
Opened 2022-11-01 18:36 UTC by Mo7amm1d

Adding an example to make it easier to get started using the middleware.

2022-11-02 14:34 UTC, tylerlaceby requested changes
I think it is a good idea to add examples to the readme however this is not how the library is supposed to be used xD.

the way to access files uploaded is ```ts
req.files
// or formData
req.formData
```

2022-11-02 19:58 UTC, Mo7amm1d commented
For some reason, the 

req.files
req.formData

are both undefined.

When I logged the req, the parsedBody was as follow:

```ts
parsedBody: {
    files: [
      {
        filename: "313400139_1020273502170152_2936886678058206448_n.jpg",
        type: "image/jpeg",
        content: [Uint8Array],
        size: 88300
      }
    ],
    formData: {
      file: [Function: file],
      value: [Function: value],
      entries: [GeneratorFunction: entries],
      removeAll: [AsyncFunction: removeAll],
      [Symbol(Symbol.iterator)]: [Function: [Symbol.iterator]]
    }
  },
```

I could access the uploaded file in req.parsedBody.files, but In my application, I also needed to access the values passed with the files through the form. 

That's the reason why I used the file() function and value() function to extract the values manually using the Values defined in the form.


If there's another way, can you provide it, please?

2022-11-02 23:22 UTC, tylerlaceby commented
So you want the key from the form as well for the files object ? 

Yea I can w tend it. Also should I be putting the data on the req.parsedBody be default. 

This is my first middleware and I'm only writing it as a proof of concept for work currently.

2022-11-02 23:23 UTC, tylerlaceby commented
Like maybe I'll add to the files[] the form name as a property.

2022-11-03 09:57 UTC, Mo7amm1d commented
> So you want the key from the form as well for the files object ?
> 
> Yea I can w tend it. Also should I be putting the data on the req.parsedBody be default.
> 
> This is my first middleware and I'm only writing it as a proof of concept for work currently.

Nah, you don't. ```req.body``` will automatically put it in parsedBody. So setting it to ```req.body``` is correct.

```req.body.files``` are where the files would be, but the fields are not parsed within the code.

I have modified the code to parse the other parameters passed with the file, and have set it to ```req.body.fields```

You're doing a great job.

I will open a different PR for Implementing the Fields part.

2022-11-03 09:58 UTC, Mo7amm1d commented
> Like maybe I'll add to the files[] the form name as a property.

I think It may be better if you separate it from the ```files[]```.

2022-11-03 13:05 UTC, merged